### PR TITLE
Improve header parsing

### PR DESCRIPTION
**Pull request by leonard-thieu**
Ref: https://github.com/DefinitelyTyped/definition-header/pull/15#issuecomment-304804860

**Summary of changes**
- Line/column numbers in errors were off by 1
- Add reason for failure on repo tests
- Fix handling of parentheses in label
- Handle author names with unexpected characters (e.g. ',' or '&')
- Made parsing of multiple authors more flexible
  - Allow mixing same-line and multi-line formats
  - Allow trailing comma and whitespace for multi-line format
  - Allow variable space at beginning of new line for multi-line format
- Allow [spaces in repo URL](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a1df15ca42d8d962f8bf48de8eaafb8618712a1/types/sharepoint/index.d.ts#L4)
- Allow [noise after project URL](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5a1df15ca42d8d962f8bf48de8eaafb8618712a1/types/js-data-http/index.d.ts#L2)

This fixes 59 out of 60 failing test cases. The exception is jQuery's version header which I couldn't figure out how to handle (and should probably be fixed in the type definition anyway).

### CODE REVIEW

**Comment by leonard-thieu** [comment]
Fixed jQuery's header in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/16768 so build should start passing when that's merged.

**Comment by leonard-thieu** [comment]
@vvakame, this handles the jQuery case now. Should be good to go.

**Comment by leonard-thieu** [comment]
@vvakame mind taking a look?

**Comment by vvakame** [comment]
sorry for late. thank you for your awesome works!

**Comment by vvakame** [comment]
I updated this package & dt-review-tool & dt-review-bot. thanks!

Do you want to access grant to this repository?
I am very happy to help with maintenance!
cc/ @DefinitelyTyped/owners

**Comment by leonard-thieu** [comment]
Sure, that sounds good to me.

**Comment by vvakame** [comment]
I added you to DefinitelyTyped/infrastructure team! have fun 😉

**Pull request merged**
